config/routes.rb
Rails.application.routes.draw do

	root 'welcome#home'

	resources :todos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
  	@todo = Todo.all
  	@todo1 = Todo.new
  	# @todo2 = Todo.find(params[:id])
  end

  def show
  	@todo = Todo.find(params[:id])
  end

  def completed
  	@todo = Todo.find(params[:id])
  end

  def new
  	@todo = Todo.new
  end

  def create
  	@todo = Todo.new(todo_params)

  	if @todo.save
  		redirect_to todos_path
  	else
  		render :new
  	end
  end

  def edit 
  	@todo = Todo.find(params[:id])
  end

  def update
  	@todo = Todo.find(params[:id])

  	if @todo.update(todo_params)
  		redirect_to todos_path(@todo)
  	else
  		render :edit
  	end
  end

  def destroy
  	@todo = Todo.find(params[:id])
  	@todo.destroy
  	redirect_to todos_path
  end

  private

  def todo_params
  	params.require(:todo).permit(:item, :description, :complete, :priority)
  	
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  	@todo = Todo.all
  	@todo1 = Todo.all.where(complete: false, priority: false).count
  	@priority = Todo.all.where(priority: true).count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %> |
<%= link_to 'To Do List', todos_path %> |
<%= link_to 'Add Item', new_todo_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  	<%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/todos/completed.html.erb
<h1> Completed Items List </h1>
<%= link_to 'All Items', todos_path %>
<% @todo.each do |listed| %>
	<% if listed.complete %>
		<h3><%= link_to listed.item, todo_path(listed) %></h3>
	<% else %>
		<h3>Nothing to see here</h3>
	<% end %>
<% end %>	

app/views/todos/edit.html.erb
<h1>Edit To Do list item</h1>
<%= form_for @todo do |f| %>
	<%= f.label :item %>
	<%= f.text_field :item %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<%= f.label :priority %>
	<%= f.check_box :priority %>
	<%= f.label :complete %>
	<%= f.check_box :complete %>
	<%= f.submit %>
<% end %>

app/views/todos/index.html.erb
<h1> To Do List </h1>
<hr />
<%= form_for @todo1 do |f| %>
	<%= f.label :item %>
	<%= f.text_field :item %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<%= f.submit %>
<% end %>

<h2>Priority Items:</h2>
	<% @todo.each do |listed| %>
		<% if listed.priority %>
			<h3><%= link_to listed.item, todo_path(listed) %></h3>
		<% end %>
	<% end %>

<hr />

<h2>Still left to do:</h2>
	<% @todo.each do |listed| %>

		<% if listed.complete || listed.priority == true %>
			<h3></h3>
		<% else %>
			<h3><%= link_to listed.item, todo_path(listed) %></h3>
		<% end %>
	<% end %>
<hr />

<h2>Completed</h2>
<% @todo.each do |listed| %>
	<% if listed.complete %>
		<h3><strike><%= link_to listed.item, todo_path(listed) %></strike></h3>
	<% else %>
		<h3></h3>
	<% end %>
<% end %>	
<hr />

<%= link_to 'All', todos_path %>
<%= link_to 'Completed List', todos_path %>
<%= link_to 'To be done List', todos_path %>
	

app/views/todos/new.html.erb
<h1>Add a new To Do Item !!</h1>
<%= form_for @todo do |f| %>
	<%= f.label :item %>
	<%= f.text_field :item %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<%= f.submit %>
<% end %>

app/views/todos/show.html.erb
<h1>List Item</h1>
<h2> <%= @todo.item %> </h2>
<h2> <%= @todo.description %> </h2>
<%= link_to 'Edit Item', edit_todo_path(@todo) %> ||
<%= link_to 'Delete Item', todo_path(@todo), method: :delete %>
<p>Click edit to mark complete</p>
<p> </p>
<%= link_to 'Back', todos_path %>

app/views/welcome/home.html.erb
<h1>Welcome to your To Do List !!</h1>
<h2>You have <%= @priority %> Priority Items still remaining:</h2>
	<% @todo.each do |listed| %>
		<% if listed.priority %>
			<h3><%= listed.item %></h3>
		<% end %>
	<% end %>

<hr />

<h2>You have <%= @todo1 %> items still left to do:</h2>
	<% @todo.each do |listed| %>

		<% if listed.complete || listed.priority == true %>
			<h3></h3>
		<% else %>
			<h3><%= listed.item %></h3>
		<% end %>
	<% end %>
<hr />